apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-kotlin-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace:
  project: default
  sources:
  - path: overlays/dev
    repoURL: https://github.com/rafal-slowik/argocd-infra.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
