apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-kotlin
  name: spring-kotlin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-kotlin
  template:
    metadata:
      labels:
        app: spring-kotlin
    spec:
      containers:
      - image: rafal0823/springkotlin:master4d982c711700417333
        name: springkotlin
status: {}